# Generated by Django 5.2.5 on 2025-08-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledemo',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
