# Generated by Django 5.2.5 on 2025-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profiledemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledemo',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('maintain', 'Maintain'), ('gain_muscle', 'Gain muscle')], max_length=20),
        ),
    ]
