# Generated by Django 5.2.5 on 2025-08-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weightentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightentry',
            options={'ordering': ['-recorded_at']},
        ),
    ]
