# Generated by Django 5.2.5 on 2025-08-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profiledemo_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledemo',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose'), ('maintain', 'Maintain'), ('gain', 'Gain')], max_length=20),
        ),
    ]
