# Generated by Django 5.2.5 on 2025-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_weightentry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledemo',
            name='weight',
            field=models.FloatField(),
        ),
    ]
