# Generated by Django 5.2.5 on 2025-11-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
