# Generated by Django 5.2.5 on 2025-12-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meal_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='portion',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_generated', 'AI Generated')], default='manual', max_length=20),
        ),
    ]
