# Generated by Django 5.2.5 on 2025-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_meal_name_remove_meal_portion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
