# Generated by Django 5.2.5 on 2025-12-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_meal_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='date_logged',
            new_name='date',
        ),
    ]
