# Generated by Django 5.2.5 on 2025-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
