# Generated by Django 5.2.5 on 2025-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
