# Generated by Django 5.2.5 on 2025-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_meal_is_eaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledemo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
